version: "3.8"

services:
  messenger:
    image: "rabbitmq:latest"
    expose:
      - "5672"
      - "15672"
  authentication-api-cache:
    image: "redis:latest"
    expose:
      - "6379"
    volumes:
      - ".:/app"
    command: "/app/wait-for-it.sh messenger:5672 -- redis-server --requirepass ${AUTH_CACHE_PASSWORD}"
    depends_on:
      - "messenger"
  registration-api-cache:
    image: "redis:latest"
    expose:
      - "6379"
    volumes:
      - ".:/app"
    command: "/app/wait-for-it.sh authentication-api-cache:6379 -- redis-server --requirepass ${REGISTRATION_REDIS_DB_PASSWORD}"
    depends_on:
      - "authentication-api-cache"
  authentication-api:
    build:
      context: "./authentication-api"
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
      - "/app/authentication-api/node_modules"
    environment:
      - "NODE_ENV=DEVELOPMENT"
      - "MONGO_DB_URL=${MONGO_DB_URL}"
      - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
      - "AUTH_CACHE_PASSWORD=${AUTH_CACHE_PASSWORD}"
      - "GOOGLE_OAUTH_SECRET=${GOOGLE_OAUTH_SECRET}"
      - "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}"
      - "GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}"
    expose:
      - "80"
    depends_on:
      - "registration-api-cache"
  registration-api:
    build:
      context: "./registration-api"
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
      - "/app/registration-api/node_modules"
    environment:
      - "NODE_ENV=DEVELOPMENT"
      - "MONGO_DB_URL=${MONGO_DB_URL}"
      - "PASSWORD_RESET_JWT_SECRET_KEY=${PASSWORD_RESET_JWT_SECRET_KEY}"
      - "EMAIL_CONFIRMATION_JWT_SECRET_KEY=${EMAIL_CONFIRMATION_JWT_SECRET_KEY}"
      - "REGISTRATION_REDIS_DB_PASSWORD=${REGISTRATION_REDIS_DB_PASSWORD}"
      - "GMAIL_ADDRESS=${GMAIL_ADDRESS}"
      - "GMAIL_PASSWORD=${GMAIL_PASSWORD}"
    expose:
      - "80"
    depends_on:
      - "authentication-api"
  users-api:
    build:
      context: "./users-api"
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
      - "/app/users-api/node_modules"
    environment:
      - "NODE_ENV=DEVELOPMENT"
      - "MONGO_DB_URL=${MONGO_DB_URL}"
    expose:
      - "80"
    depends_on:
      - "registration-api"
  server:
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
    ports:
      - "80:80"
    depends_on:
      - "users-api"
